services:
  mysql:
    container_name: mysqldb
    image: mysql
    restart: always
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=movie_app
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456789
    volumes:
      - mysql-data:/var/lib/mysql
      - ./movie_app.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net
  backend:
    container_name: backend-movie
    image: thuanvn2002/movie-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-net
    depends_on:
      - mysql
  frontend:
    container_name: frontend-movie
    image: thuanvn2002/movie-frontend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-net
    depends_on:
      - backend
volumes:
  mysql-data:


networks:
  app-net:
    driver: bridge
