server:
  port : 8082
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: '3600000'
      refresh-token:
        expiration: '86400000'
  service:
    user:
      userPerPage: '5'
    movie:
      moviePerPage: '5'
    room:
      roomPerPage: '5'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  datasource:
    password: '123456789'
    username: admin
    url: jdbc:mysql://mysqldb:3306/movie_app
payment:
  vnPay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    tmnCode: "EDT2E52Y"
    secretKey: "VGC6H4EJ834TXE5USIHM20W3FH4469VW"
    returnUrl: "http://localhost:8080/vn-pay-callback"
    version: "2.1.0"
    command: "pay"
    orderType: "bill"